#spring:
#  application:
#    name: todo-service
#  kubernetes:
#    config:
#      name: todo-service
#      namespace: default-namespace
#      sources:
#        - name: c1
#    reload:
#      enabled: true
#    secrets:
#      name: db-secret
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_example
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
#  jpa:
#    showSql: true
#    hibernate:
#      ddlAuto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
#server:
#  port: 8081
#
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
##  instance:
##    preferIpAddress: true